# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nsq-ruby 2.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "nsq-ruby".freeze
  s.version = "2.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Wistia".freeze]
  s.date = "2016-12-29"
  s.description = "".freeze
  s.email = "dev@wistia.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "README.md",
    "lib/nsq.rb",
    "lib/nsq/client_base.rb",
    "lib/nsq/connection.rb",
    "lib/nsq/consumer.rb",
    "lib/nsq/discovery.rb",
    "lib/nsq/exceptions.rb",
    "lib/nsq/frames/error.rb",
    "lib/nsq/frames/frame.rb",
    "lib/nsq/frames/message.rb",
    "lib/nsq/frames/response.rb",
    "lib/nsq/logger.rb",
    "lib/nsq/producer.rb",
    "lib/version.rb"
  ]
  s.homepage = "http://github.com/wistia/nsq-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Ruby client library for NSQ".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<nsq-cluster>.freeze, ["~> 1.1"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.0"])
    else
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<nsq-cluster>.freeze, ["~> 1.1"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<nsq-cluster>.freeze, ["~> 1.1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.0"])
  end
end

