name: Run Tests
on: push

jobs:
  test:
    strategy:
      matrix:
        ruby_version: ['2.7', '3.0', '3.1', '3.2']
    runs-on: ubuntu-22.04
    steps:
      - name: Install NSQ
        shell: bash
        run: |
          wget https://github.com/nsqio/nsq/releases/download/v1.2.1/nsq-1.2.1.linux-amd64.go1.16.6.tar.gz
          tar xvzf nsq-1.2.1.linux-amd64.go1.16.6.tar.gz
          mv nsq-1.2.1.linux-amd64.go1.16.6/bin/* /usr/local/bin

      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run tests
        shell: bash
        run: |
          echo "path: $PATH"
          bundle exec rspec spec
